// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING

// Importing the Quasar feature-flag module
require("quasar/dist/types/feature-flag");

// Extending the QuasarFeatureFlags interface
module.exports = function (QuasarFeatureFlags) {
  QuasarFeatureFlags.store = true;
};
